stm32-rs/stm32l0xx-hal

- .travis.yml
- build.rs
- examples/button.rs
- examples/button_irq_rtfm.rs
- examples/i2c.rs
- examples/serial.rs
- src/adc.rs
- src/exti.rs
- src/gpio.rs
- src/i2c.rs
- src/prelude.rs
- src/pwm.rs
- src/rcc.rs
- src/serial.rs
- src/timer.rs
Sorry - I just realized with this PR that my `cargo fmt` touched a lot of stuff that I didn't mean to touch. That being said, it's probably worth adding a `cargo fmt` check to CI to I've added that to `.travis.yml`.
Other than that, my main goal was to rebase the branch that I've been building a project off of. Mainly bug fixes to EXTI and GPIO but I also make the UART peripheral names public.
One problem that is _not_ fixed in this branch is that the `flush` in `write_str` seems to throw errors consistently, at least on my platform.
> Bug fixes to EXTI and GPIO

- examples/aes-dma.rs
- src/dma.rs
This pull request is based on #14. I recommend reviewing/merging that pull request first, before this one.
I have additional commits to test this against the Tlera Corp Gnat here:
https://github.com/braun-embedded/stm32l0xx-hal/compare/dma-interrupts...braun-embedded:dma-interrupts-gnat
cc @lthiery
> Add support for interrupts to DMA API

- Cargo.toml
- src/dma.rs
- src/pwm.rs
- src/timer.rs
I've been having some problems with mismatched `cortex-m` versions, so I figured, why not just update everything.
> Update all dependencies to their latest versions

- examples/aes_ctr_dma.rs
- examples/button_irq.rs
- examples/exti_wakeup.rs
- examples/rtc_wakeup.rs
- examples/serial_dma.rs
- examples/timer.rs
- src/exti.rs
This is a breaking change, because EXTI API is changed.
> Fix NVIC deprecation warnings

- src/timer.rs
This just adds an API for user to reset the counter
> add reset api to Timer

- Cargo.toml
- build.rs
This is useful if the user wants to supply their own linker script.
> Add Cargo feature to disable linker script

- Cargo.toml
- examples/rng.rs
- src/lib.rs
- src/rcc.rs
- src/rng.rs
- src/usb.rs
This is based on and supersedes @lthiery's #50.
I've made the following changes:
- Made it possible to use RNG and USB at the same time.
- Made in compile on STM32L0x1.
- Fixed warnings in RNG example.
@lthiery Please let me know what you think.
Close #50
> Add RNG API

- .travis.yml
- Cargo.toml
- examples/usb_serial.rs
- src/lib.rs
- src/usb.rs
See also: https://github.com/stm32-rs/stm32-usbd/pull/16
cc @hannobraun
> Add USB driver and example

- examples/lptim.rs
- src/exti.rs
- src/lib.rs
- src/lptim.rs
Builds on top of #51 since some SVD fixes are necessary to make this work on the stm32l0x2/x3 chips.
> Low-Power Timer support

- src/serial.rs
Built on top of #71 
Mainly this adds a method to query pending events.
> Improve the UART IRQ / Event API

- src/serial.rs
> Improve serial error handling

- src/flash.rs
Back when I implemented this, I was under the assumption that 1 wait
state was a safe default value that should work for all configurations,
although not always be optimal. This turned out to be wrong.
I've seen a weird case, where the USB peripheral could get into a state
where it would no longer send data. This only happened with the number
of wait states set to 1. I don't know how other voltage range and core
frequency configurations might affect this.
I think the best option to now is to leave this configuration up to the
user, which is why I've added a method to the Flash API to configure it.
> Do not set flash wait states to 1 by default

- Cargo.toml
Should fix the build on docs.rs
> docs.rs: build for thumbv6m-none-eabi target

- examples/adc_cont.rs
- examples/adc_multi.rs
- examples/adc_trig.rs
Three of them were not yet adjusted for the changes in #68.
> Fix ADC examples

- src/pwm.rs
- Add start, stop method that allow user to run
timer on demand
- Allow user to update frequency without the need to
drop the timer instance
- Allow user to free the pac timer in order to properly
use it elsewhere
> pwm: Improve usability of HAL pwm

- Cargo.toml
- examples/button_irq_rtfm.rs
- examples/timer_interrupt_rtfm.rs
I tested the timer example, works as before.
The button example is untested but compiles without any warning.
Upgrade notes: https://rtfm.rs/0.5/book/en/migration.html
> Port examples to RTFM 0.5

- src/rcc.rs
> Maximum frequency for stm32l0 increased to 32MHz

- src/lptim.rs
As per the title, adds support for turning on encoder mode for LPTIM. e.g.
```rust
let mut pwr = PWR::new(dp.PWR, &mut rcc);
let lptim = LpTimer::init_encoder(
dp.LPTIM,
&mut pwr,
&mut rcc,
ClockSrc::Hsi16,
(gpiob.pb5, gpiob.pb7),
// Roll over at 4096
4096,
);
defmt::info!("Count {:?}", lptim.count());
```
> Add QEI support for LPTIM

- Cargo.toml
- examples/serial_lse.rs
- src/rcc.rs
- src/serial.rs
> Adds support of LSE clocking to LPUART

- Cargo.toml
- README.md
> Release version 0.7.0

- src/gpio.rs
> fixed missing `!` operator

- CHANGELOG.md
- Cargo.toml
- examples/temperature.rs
This example builds but has not been tested on hardware.
> added example temperature.

- src/i2c.rs
- src/lib.rs
- src/serial.rs
This should hopefully fix all issues reported by Clippy.
Resolves #163.
> Fix clippy warnings

- Cargo.toml
- src/dma.rs
sorry for the double PR, i accidentally deleted my #167 branch... 
anyway, here we go, i added the comments, your remarks were spot on.
> fixed update and added comments to unsafe dma access

- CHANGELOG.md
This adds entries in the changelog for PR #173  and #174
> Add changelog entries for PR #173 & #174

- CHANGELOG.md
- Mention fully erased GPIO pins (#190)
- Fix some issue references
> Changelog improvements

- CHANGELOG.md
- Cargo.toml
- README.md
> Release version 0.8.0

- CHANGELOG.md
- Cargo.toml
- README.md
- RELEASING.md
Replaces #205.
This also adds a `RELEASING.md` file as internal documentation.
> Release 0.9.0

- README.md
I guess that should do. What do you think, @jamwaffles?
Closes #211.
> README: Add call for maintainers

- src/timer.rs
Small PR to add pause/resume to the timers
> Added pause & resume to timer control

- src/flash.rs
- src/i2c.rs
- src/pwm.rs
As per the title. Some of the lints picked up some code cleanups, but there are some others that I needed to shush clippy about because we know they're safe but it doesn't...
> Fix a bunch of clippy lint errors
