stm32-rs/stm32l0xx-hal

Cargo.toml, examples/blinky.rs, examples/blinky_delay.rs, examples/button.rs, examples/button_irq.rs, examples/serial.rs, examples/timer.rs, src/lib.rs, src/prelude.rs, src/serial.rs, src/spi.rs, src/time.rs, src/timer.rs
I've added in minimal support for the stm32l0x2. In particular, I've tested UART and SPI and done some pin-to-AF mappings for the chip.
In an effort to get SPI working I added in the alternate function configuration of the pins to the driver, similar to how it was done in UART.
Also, it appears that embedded-hal is deprecating the pin interfaces that this project uses, so there's a flood of warnings about that. I may be able to try to resolve that but just wanted to give you a heads up.
=> minimal stm32l0x2 support. Alternate Function setup for SPI pins

src/i2c.rs
As the title says. More info in the commits.
I have an example program I tested this with. I figured it doesn't make sense to add a million example using whatever hardware people have lying around, so I kept it separate. Here it is:
https://github.com/braun-embedded/stm32l0xx-hal/blob/2250f59525407dd6564565736691804a80b83898/examples/i2c.rs
cc @lthiery
=> Add STM32L0x2 support to I2C API

jlink.gdb, src/exti.rs, src/gpio.rs
Found some more bugs in exti; in particular, write instead of modify was disabling extiN configurations for any of the pins that share the same exti register. 
In addition, bitmask mapping for PH was wrong.
I've also added a gdb script that works for jlink.
=> Added jlink.gdb. Fixed exti bug and more detail around stm32l0x2 ports

.travis.yml, Cargo.toml, examples/adc.rs, src/adc.rs, src/lib.rs, src/prelude.rs
As the title says. Details in the commits.
This pull request shares its first commit with #13. To keep the history as clean as possible, it might make sense to merge one of the first, then wait until I have rebased the other one.
cc @lthiery
=> Make ADC work on STM32L0x2, some fixes

Cargo.toml, examples/aes-dma.rs, src/aes.rs, src/dma.rs, src/lib.rs
Also adds a generic DMA module that can be reused by other peripheral APIs.
This pull request is based on #13. I recommend reviewing and merging that pull request before this one.
=> Add DMA support to AES module

Cargo.toml, examples/aes-dma.rs, src/aes.rs, src/dma.rs
This pull request changes the AES API to work with `u8` buffers, instead of `u32` buffers, which should make it easier to use in most scenarios.
I've also snuck in a few commits that fix and improve some other things related to AES and DMA. It didn't seem worth it to create a separate pull request for those, especially since I've already got a bit a bit of a traffic jam going :-)
This pull request is based on #16. I recommend reviewing/merging that one first.
cc @lthiery
=> Make DMA-based AES API more ergonomic

Cargo.toml, examples/aes-dma.rs, examples/serial_dma.rs, src/aes.rs, src/dma.rs, src/serial.rs
Also contains some small cleanups of the `serial` module.
This pull request is based on #19. I recommend reviewing/merging that pull request first.
cc @lthiery
=> Add DMA support to USART API

Cargo.toml, examples/adc_pwm.rs, examples/pwm.rs, src/gpio.rs, src/prelude.rs, src/pwm.rs
This is a big clean-up effort of the `pwm` module. It fixes the following problems:
- The module was a bit of a mess, with lots of duplicated code.
- Some of the `unsafe` access to timer registers was unsound, as it didn't take race conditions into account.
- The module was not flexible enough to support STM32L0x2 fully.
Overall, I believe that this new approach, with each channel being its own struct that can be configured separately, is a step in the right direction. In fact, I think we should consider using the same approach for the `timer` module, maybe even merge both modules. (I'm not sure if the hardware supports this, but if both modules were merged it could be possible to use one channel for PWM, another for something else, e.g. as a hardware trigger for ADC.)
cc @lthiery
=> Clean up PWM code, fix race conditions, improve STM32L0x2 support

examples/exti_wakeup.rs, src/exti.rs, src/lib.rs, src/prelude.rs, src/pwr.rs, src/rcc.rs
Add a PRW API with support for Sleep and Stop modes, as well as a method that goes to sleep and waits for an EXTI interrupt. I also snuck in some clean-up of the `prelude` module, while I was in there.
cc @lthiery
=> Add PWR API, support for wake-up via EXTI

Cargo.toml, examples/rtc.rs, examples/rtc_low_apb1.rs, src/lib.rs, src/pwr.rs, src/rtc.rs, src/time.rs
This pull request adds a very basic RTC API. It can be used to read and set the time, but no alarms or other interrupts are supported yet. There are also a few commits adding general debug stuff to the `time` module, as that was useful to me while I developed this.
I'm marking this PR as a draft, as it's based on #25. Otherwise, this is ready to review.
cc @lthiery
=> Add basic RTC API

examples/rtc_wakeup.rs, src/exti.rs, src/rtc.rs
As the title says, this pull requests adds support for waking up from low-power modes using the RTC wakeup timer. In addition it adds some fixes of and improvements upon my previous RTC PR.
It also makes some changes to the EXTI API that are required to support the RTC wakeup timer. The new capabilities are basically duct-taped on top of the old ones, which leads to some weird issues (like the `listen`'s `port` argument being ignored when it doesn't make sense).
This is far from the ideal approach, and I believe there's a possible EXTI API that is much more type-safe and has more natural support for non-GPIO interrupts. However, I don't have the time to figure that out right now.
I plan to go back and take a look at an EXTI redesign after I've completed some more urgent task. Probably …
=> Add support for wakeup via RTC wakeup timer

examples/rtc_wakeup.rs, src/exti.rs, src/pwr.rs, src/rtc.rs
Adds support for entering Standby mode, as well as wake-up from Standby mode via RTC. Also includes a bunch of fixes and cleanups of earlier work.
cc @lthiery
=> Add support for entering Standby mode

examples/button_irq.rs, examples/button_irq_rtfm.rs, examples/exti_wakeup.rs, examples/rtc_wakeup.rs, src/aes.rs, src/exti.rs, src/lib.rs, src/rcc.rs, src/syscfg.rs, src/usb.rs
Details in the commits!
Working example here: https://github.com/braun-embedded/rust-catena-4610/pull/3
I haven't submitted an example here yet, as that would depend on my fork of `stm32-usbd`.
Related: https://github.com/stm32-rs/stm32-usbd/pull/7
cc @lthiery
=> Add support for USB

Cargo.toml
Blocked on https://github.com/stm32-rs/stm32l0xx-hal/pull/30
See also: https://github.com/stm32-rs/stm32l0xx-hal/pull/32
=> Bump version (0.3.0)

Cargo.toml, examples/serial_dma_async.rs, src/dma.rs
I was trying to put together an 'async' DMA example that basically continues looping without waiting for DMAs to finish but I ran into some issues.
As according to the comments for `wait`:
```
/// [wait] will busily wait until the transfer is finished. If you
/// don't want this, please call this function only once you know that the
/// transfer has finished.
```
I assumed the only other Transfer function, `is_active`, was the intended way of checking this (@hannobraun). Unfortunately, it modifies the registers when returning false, meaning a non-blocking call to `wait` after checking `active` would get stuck in `wait`. That is to say, the following fails:
```
if !transfer.is_active() {
// gets stuck because internal calls to `is_active` always returns true
transfer.wait();
}
```
I've …
=> dma fix and dma_async example

src/gpio.rs, src/i2c.rs, src/serial.rs
Add all possible pin assignments. 
Only following assignments tested with real HW:
LPUART1, PA2, PA3,  AF6;
USART4, PA0,  PA1,  AF6;
=> Add LPUART1, USART4, USART5 support for stm32l0x3

Cargo.toml
It isn't needed as a normal dependency, and pulls in an old cortex-m version (0.5.x).
=> Make RTFM a dev-dependency

src/aes.rs, src/dma.rs, src/i2c.rs, src/serial.rs
Addresses #41
Required adding `num_words` parameter to `Transfer::new(..)`.  `Transfer::new(..)` will panic if the provided transfer size is larger than the provided buffer length (in words).
=> Added write_some and read_some methods to I2c and UART peripherals

examples/pwr.rs, src/pwr.rs
This adds complete support for entering all low-power modes supported by the hardware. Also contains a commit with a small PWR-related fix.
=> Add support for low-power run/sleep mode

Cargo.toml, src/i2c.rs, src/serial.rs, src/spi.rs
Tested only on stm32l0x2, but as I understand it, stm32l0x3 is a superset of stm32l0x2?
=> Add SPI2, LPUART, and I2C definitions for stm32l0x2/3

src/timer.rs
The following will not behave correctly. 
```
loop {
timer.start(6.ms());
block!(timer.wait());
timer.start(60.ms());
block!(timer.wait());
}
```
One would expect that we first wait for 6 ms and then for 60 ms, but since the prescaler counter is not reset between consecutive starts the timing will not be accurate for the second and following calls, in particular if the prescaler factor (PSC-register) had to be changed in `start`.
By setting the UG-bit in EGR the counters will be reset such that each call to `start` will behave the same. 
A similar thing is done in the corresponding timer function in [stm32f1xx-hal](https://docs.rs/stm32f1xx-hal/0.4.0/src/stm32f1xx_hal/timer.rs.html#187).
This was tested on the STM32L051K8U6.
=> Make sure the prescaler counter is reset when starting a timer

src/exti.rs, src/rcc.rs
This saves 1.5 KiB of binary size in the `pwr.rs` example.
See comments for explanations.
=> Mark a few functions as inline

examples/usb_serial.rs, src/usb.rs
This improves the `usb` module, bringing it more in line with other modules and making the API less error-prone.
=> Improve USB module

src/gpio.rs
This allows accessing these values without needing the pin instance,
and works in a const context.
=> Add associated consts for port and pin number

src/lib.rs
Breaking change (and potentially controversial).
Closes #61
=> Remove the `device` and `stm32` reexports

src/rcc.rs
This change fixes a bug wherein the PLL is never ready since the code to enable the PLL has some problematic writes that turn off the HSE or HSI osc input.
The PLL enable code included `self.cr.write` where we needed `self.cr.modify` to prevent the other register bits from resetting to default. The svd2rust register write resets everything. Modify changes bits without touching others.
=> Fix PLL enable.

examples/serial_dma_async.rs, src/exti.rs, src/gpio.rs
For some reason, GPIOC and GPIOD were disabled for the stm32l0x1, but these GPIO banks are present in the PAC (and in the datasheet).
=> gpio: Enable all GPIO for all targets

src/gpio.rs, src/pwm.rs, src/serial.rs
This eliminates a frequent annoying pattern in embedded Rust when having to dynamically change the configuration of a pin. Where you previously would have to dance the `Option` dance:
```rust
static mut PIN: Option<PB2<Input<Floating>>> = ...;
let mut out = PIN.take().unwrap().into_push_pull_output();
// do stuff with `pin`
PIN = Some(out.into_floating_input());  // put it back
```
With this API you can instead do this:
```rust
static mut PIN: PB2<Input<Floating>> = ...;
PIN.with_push_pull_output(|pin| {
// do stuff with `pin`
});
```
Of course, this doesn't fix cases where the configuration changes *globally* and would need to be stored back into the `PIN` resource, but it should still be helpful.
Please carefully review the bit manipulation ~~as I have not yet tested this~~ (I have …
=> Add an API for temporary GPIO reconfiguration

Cargo.toml, examples/adc_cont.rs, examples/adc_multi.rs, examples/adc_trig.rs, src/adc.rs, src/aes.rs, src/dma.rs, src/i2c.rs, src/serial.rs, src/timer.rs, src/usb.rs
Adds support for continuous conversions via DMA to the ADC API. This is of somewhat limited use (as the example shows), as it's impossible to process the data as fast as the ADC can produce it. It requires support for hardware triggers, to become fully usable.
However, this PR adds some valuable infrastructure, like circular DMA transfers and the DMA buffer code in `adc`. I think it's worth getting it merged, as it's a solid base to build upon (which I intend to do).
=> Add support for continous conversions to ADC

Cargo.toml, examples/rtc.rs, examples/serial.rs, examples/serial_dma.rs, examples/serial_dma_async.rs, src/dma.rs, src/lib.rs, src/prelude.rs, src/serial.rs
Based on #66, merge that first. Fixes #67.
The previous approach with the `Pins` trait assumed that an USART
peripheral can only be used with specific pin pairs. However, pins can
be mixed, so you could use USART1 with PA9 and PB7.
So instead of the `Pins` trait, there are now separate `TxPin` and
`RxPin` traits. They are implemented for all pins of all U(S)ART
peripherals of the stm32l0xx family.
Pin mappings verified against datasheets of stm32l071kb, stm32l072vz
and stm32l083vz.
=> Serial: Replace `Pins` trait with `TxPin` / `RxPin`

Cargo.toml, build.rs, src/dma.rs, src/i2c.rs, src/lib.rs, src/prelude.rs
The GPIO internal peripheral (IP) does not match the stm32l0x/stm32l0x2/stm32l0x3 grouping used in the PACs. Instead, there are 4 different GPIO IPs in the STM32L0 family that define how the pin functions are mapped to the actual pins. This means that the current I2C mappings are broken for a lot of MCUs. For reference, these issues have already been opened because the mappings were broken:
- https://github.com/stm32-rs/stm32l0xx-hal/pull/76
- https://github.com/stm32-rs/stm32l0xx-hal/issues/77
- https://github.com/stm32-rs/stm32l0xx-hal/issues/85
We can use the `io-*` Cargo features to differentiate between these mappings. This requires that the proper `io-*` feature is set when compiling (and is thus a breaking change). The easiest way to apply the feature without looking at the …
=> Update I2C pin mappings based on STM32L0xx GPIO IP

Cargo.toml
Initially I was fairly confused on what those "GPIO IP versions" actually mean, but now I'm pretty sure they correspond to the product categories as per "1.4 Product category definition" in the family reference manual.
For example, in the stm32l0x1 Reference Manual:
=> Add comments about product categories to io-* features

src/serial.rs
Unfortunately a typo sneaked into the `serial` module in #68. This PR fixes compilation on `io-STM32L021`.
=> Serial: Fix compilation for io-STM32L021

Cargo.toml
MCU features should only serve as aliases, they should *not* be used in
`cfg` attributes, since the resulting code would be unmaintainable in
the long run.
=> Cargo.toml: Add usage warning to MCU feature comment

.travis.yml
This should prevent #92 from happening again, by including all four `io-*` features in CI.
If all works well, some tests in this PR should fail.
If that is confirmed, merging #93 and #95 and rebasing should make the tests pass.
=> Travis: Test all io-* features in build matrix

src/rcc.rs
Source (reference manual page 181):
=> Document MSIRange enum variants

src/i2c.rs
Hi, I discovered a couple of issues with the blocking I2C driver while playing around with an 32L0538DISCOVERY board. This board has a custom I2C slave peripheral to measure the current of the main STM32 controller, and while writing a driver for it I stumbled upon some bugs in the HAL driver. 
Could someone take a look at these changes and see if they can make it into the library?
=> Made improvements to polling i2c driver

src/timer.rs
Tested the interrupt on an STM32L071KBTx, seems to work fine. The `CountDown` impl was not tested, but I don't see a reason why it shouldn't work.
I would have added TIM7 as well, but the PAC does not yet expose it.
Note that not all models have TIM6 / TIM7.
=> Add support for TIM6

src/i2c.rs
In send_byte() wait for TX fifo empty before returning Ok. It would be
better to wait for end of transmission, but there is no such field in
I2C status register.
In recv_byte() return Err if error condition detected while waiting for
byte.
Before starting new transaction ensure that both TX and RX buffers are
empty. There are some corner cases where something may be there.
=> i2c: properly handle bus errors

src/adc.rs
This is a supported configuration and I've tested it with a NUCLEO-L011K development
board and confirmed in the spec sheet that this is supported
Proposed improvement for  #123
=> Removed config tests that prevented stm32l0x1 dfevices from using ADC with DMA

src/adc.rs
I suspect that there is a timing issue with reading the flag then
clearing it in a non-atomic way. We can still use the flag to detect
overruns because it will never give a false positive, but it CAN give a
false negative it seems
Storing the position that we last witnessed the DMA as being at and
performing a wrap when that position is less than our current positon
gives a reliable detection and no fale overruns
We still examining the complete flag and the positions of the current
DMA pointer and our previous one to detect overruns since the fla will
never give a false positive
This is a fix for  #104
=> Detect rollover using positions rather than DMA flags

src/calibration.rs, src/lib.rs
This PR exposes the factory calibration data.
Verified to be working on an STM32L071KBTx. As a cross-check, I verified the memory addresses against the datasheet of the (randomly picked) STM32L053C6, they match.
Strongly inspired by the `signature` module in https://github.com/stm32-rs/stm32f4xx-hal/blob/master/src/signature.rs.
Fixes #120.
CC @rnestler
=> Expose factory calibration data

flash-code/flash.c
The manual for-loop looked a bit funny :)
(A `memcpy` would probably work as well, but is less easy to read and also results in a larger binary.)
=> Simplify flash.c

src/flash.rs
EEPROM supports single-byte writes.
This also changes the pointer type from `u32` to `usize.
=> Flash: Support writing single bytes to EEPROM

src/gpio.rs
There was a typo there... Configuring a Pin as pull-down would actually set it as a floating input.
=> fix Pin::into_pull_down_input

examples/mco.rs, src/lib.rs, src/mco.rs, src/rcc.rs
I've added MCO (Microcontroller Clock Output) support in a hopefully sensible and typesafe way.
I'm reasonably happy with the impl, but will happily take any improvements. I tested the example with my L053 Nucleo using HSI16 as the clock reference. I can get PA8 and/or PA9 to show a nice steady 2MHz, so the code seems to be working as expected.
MCO consumes the output pin, which I think the API reflects. I'm also assuming MCO is available on all variants, so nothing is feature gated in this PR.
=> Add MCO support

examples/timer_encoder.rs, src/encoder.rs, src/lib.rs, src/prelude.rs
Adds encoder (QEI) input support to TIM2 and TIM21. I've tested the interrupt handling with an RTIC 0.6 project, and have included a short non-RTIC example to get users off the ground.
This leaves a few pin combinations and a few timers without an implementation currently, as I have no way to test them (or couldn't get them working) - I'll leave that as a job for other people who need it :)
=> Add encoder input support for TIM2 and TIM21

Cargo.toml, examples/linked_timer_rtic.rs, src/timer.rs
Implementation of #114.
A `LinkedTimer` impl is initialized with two hardware timers (either TIM2/TIM3 or TIM21/TIM22). The two timers are configured in master/slave mode so that an overflow of the master timer triggers an update on the slave timer. This way, two 16 bit timers can be combined to a single 32 bit timer. (The STM32L0 does not have 32 bit timers.)
Such a linked timer allows implementing the `Monotonic` trait for the RTIC scheduler with high timer precision.
Right now the implementation does not add logic for detecting an overflow, that is left to the user. Furthermore, no prescaler is configured. And not all possible timer combinations have been implemented.
An example is provided (tested on the STM32L071KBTx). Here's the serial output:
```
Starting example
Init TIM2/TIM3... …
```
=> LinkedTimer: Implement initial version

src/rcc.rs, src/rtc.rs
As LSE used for RTC and LCD, there should be a way to init LSE without RTC. It may also be helpful in situation like in issue #117 
This change adds enable_lse() method to RCC structure that configures LSE.
RTC code is modified to use this method.
=> Adds enable_lse() method to RCC structure that configures LSE.

examples/spi_dma.rs, src/dma.rs, src/spi.rs
It's not completely clear from the reference manual if we need to deal with `SPI_SR`.`OVR` or `SPI_SR`.`RXNE` here or if this can be made more robust.
=> Add DMA support to SPI API

.gitattributes, CHANGELOG.md
Format is loosely based on keepachangelog.com, the format that a lot of
other STM32 HAL crates use as well.
The main issues with single-file changelogs is that they cause a lot of
conflict potential. One solution is writing changelog entries to
separate files, and merging those before a release. However, that
requires additional tooling and is a bit cumbersome.
Instead, I added `CHANGELOG.md merge=union` to `.gitattributes`. I'm not
sure if it always works ideally, but at least it should reduce the
conflict potential a lot. And in the case something breaks, we can
always fix it manually.
=> Add a CHANGELOG

CHANGELOG.md, src/timer.rs
Useful for initializing a `Timer` to call `start()` on later.
I suppose `timer()` creates it _and_ starts it as a sort of convenience, but it's a little silly having to pass a dummy timeout. More seriously, calling `timer()` with a dummy timeout but without `listen()` and later calling `listen()` and `start()` can cause a subtle issue, I believe. If the dummy timeout has already overflowed, the interrupt is already pending and will immediately fire, before the new `start` has expired (necessitating a `clear_irq()` call in addition to `listen` and `start`).
This PR doesn't fix that issue per se, it only avoids it for creation but I think the expected behavior for `start()` would be that it also calls `clear_irq`, WDYT?
This is a breaking change for the `GeneralPurposeTimer` trait but it …
=> Add `Timer::new` to create timer without starting

build.rs
By counting the features before the "disable-linker-script" feature is checked, it will fail even if this flag was set.
=> Allow skipping linker script

src/rtc.rs
`^` was probably intended as "power" but is XOR in this context, limiting delay to a maximum of 2 XOR 17, or ..=19
=> Fixed bad op for RTC wakeup

src/rtc.rs
fixed documentation as mentioned in [PR#156](https://github.com/stm32-rs/stm32l0xx-hal/pull/156)
=> fixed documentation error for RTC wakeup

src/lib.rs, src/signature.rs
this was talked briefely in #120, i think @hannobraun 's idea is also the easiest to add.
code was indeed copied from [stm-32-device-signature](https://github.com/stm32-rs/stm32-device-signature/blob/master/src/lib.rs), credit to @Disasm
=> added support for Device electronic signature

Cargo.toml, examples/crc.rs, src/crc.rs, src/lib.rs, src/prelude.rs
I also added an example for CRC32 (Ethernet) since User manual is unclear. It says that the default CRC config is for CRC32 (Ethernet), but only the polynomial is correct, you still need to rev in and rev out bits, as well as xor the final result.
There still is an example for custom polynomial in the header doc of the CRC file, and i think both of them combined show how to use the CRC peripheral. no changes were needed for this to work on the L0xx family.
remarks welcome
=> adding support for crc engine, shamelessly taken from stm32l4xx-hal.

README.md
Following #170 
Until a better 'fix' is available, this adds a paragraph in the readme to explain how to override the memory configuration.
It is a bit on the long side, I preferred to be complete but if it is too long I can cut down some parts. Let me know if I need to change anything. I did not test this yet, but I copied the memory.x file from here and the build.rs from the one you linked so I expect this to be good. :slightly_smiling_face:
=> Add parapgraph about flash memory size in readme

src/pwm.rs
Following discussion in #172  this adds a method to PWM channels to change the underlying timer's frequency. This allows to dynamically change the PWM frequency when we have already associated a channel with a pin. Otherwise this required unsafe to work around a partial move error because the channel was moved out of the timer struct.
In the implementation I changed `clock_frequency` on the `Instance` to not take `&self`. This allows it to be used in the channels. But this is not required, we could access the RCC register directly to avoid making a breaking change?
Compared to the timer's implementation we don't stop and start the timer before changing the frequency. I tested it on my project and it seems to work flawlessly. I'm not sure why that was required in the timer's …
=> Add set_frequency method on PWM channels

src/pwm.rs
I stumbled upon #79 trying to use `PB0`  for PWM output on a `stm32l071k8ux`.
This should add the PWM capabilities on the pins for the category 5 mcus (feature `io-STM32L071`). 
Tested and seems to work with `PB0`.
=> Add TIM3 PWM support for category 5 mcus

README.md
It hasn't been updated when we introduced the EEPROM and RAM/Flash features.
=> Update MCU alias in README

src/rcc.rs
IIRC I did test the examples when working on #183, but this error shows
up when using the PLL which none of them do. I found this when testing
with my own project code. At any rate, here's a fix for embedded-time
comparisons when using the PLL.
=> Fix max frequency assertion

README.md
The project was moved to the stm32-rs organization.
=> Update repository URL for cube-parse

CHANGELOG.md, src/serial.rs
this addresses #179 where there could be a timing where the TC clear could be done after the read, missing it. would cause deadlock sometimes if flush is used with `nb::block` because the exit condition would be missed.
remarks welcome
=> Fixed potential race condition when flushing serial

examples/blinky_downgrade.rs, examples/button_irq_rtic.rs, examples/lptim.rs, examples/pwr.rs, examples/timer_interrupt_rtic.rs, src/gpio.rs
PXi.downgrade() should erase the port identifier, allowing pins to be collected into an array. See full description here: https://github.com/stm32-rs/stm32l0xx-hal/issues/189.
Most of this is borrowed from [stm32f0xx-hal](https://github.com/stm32-rs/stm32f0xx-hal).
Still waiting on my board to arrive, so I can fully test this during board bring-up, but wanted to get the code up early.
=> PXi.downgrade() erases the port identifier as well

Cargo.toml
- Add all three main committers to authors list
- More compact dependency notation
- Sort dependencies alphabetically
=> Cargo.toml cleanup

src/adc.rs, src/dma.rs, src/rtc.rs
=> Fix new version Clippy lints

Cargo.toml
It's not actually used anywhere except in examples.
(Would be nice if we could get this into the 0.9 release #207 as well.)
=> Make cortex-m-semihosting a dev dependency

src/serial.rs
There is currently already a method `pending_event` that allows to get events when the interrupts are enabled. But the `idle` flag and the `txe` and `rxne` flags can also be used when interrupts are disabled (`idleie=0`, `txeie=0` and `rxneie=0` respectively).
This PR adds methods on `Rx` and `Tx` to read the state of those flags and reset the `idle` flag. This is inspired by https://github.com/stm32-rs/stm32f1xx-hal/blob/master/src/serial.rs#L303-L324
These methods are also more intuitive IMHO than the `pending_event` method.
We tested `is_idle` and `clear_idle_interrupt` and confirmed that it worked.
What do you guys think?
=> Add methods to check idle, tx empty and rx not empty for serial

CHANGELOG.md, src/spi.rs
This was missing other possible pins for SPI1. there still is some other to be added but i think we should find a better way to have that, kind of like it's done for serial impl...
=> Fixed missing possible pins for SPI1 for STM32L0x1 family

examples/serial_dma_async.rs, src/serial.rs
Tested the change on my STM32L051T6 board with serial_dma_async example.
I also had to fix the serial_dma_async itself as the heapless `Queue::new()` creates a queue with capacity `N-1`: https://docs.rs/heapless/0.7.1/heapless/spsc/struct.Queue.html#method.new
=> Enable USART DMA for STM32L0x1 family

.github/workflows/ci.yaml, CHANGELOG.md, Cargo.toml, examples/button_irq_rtic.rs, examples/mco.rs, examples/temperature.rs, examples/timer_interrupt_rtic.rs, src/aes.rs, src/crc.rs, src/dma.rs, src/encoder.rs, src/i2c.rs, src/timer.rs, src/usb.rs
Mostly mechanical changes resulting from the `stm32l0` crate upgrade.
I also:
1. Removed `cross` from CI as it was breaking things and I don't see the value in using it
2. Upgraded to a newer RTIC for the examples that use it
Closes #198.
=> Upgrade `stm32l0` to v0.15.1

src/exti.rs
Exti::TriggerEdge is a plain enum and it should be possible to pass it by value without move. All the other enums in the exti module behave this way too.
=> Make Exti::TriggerEdge enum behave as constant (Copy+Clone+Eq+..)

CHANGELOG.md, examples/pwr.rs, examples/rtc.rs, examples/rtc_low_apb1.rs, examples/rtc_wakeup.rs, src/aes.rs, src/rcc.rs, src/rtc.rs
RTC can be used with an internal or external Low Speed clock (LSE or LSI).  LSE is more accurate but requires an external crystal on the board.   This diff adds the possibility to select LSI or LSE when RTC is
created.
Also, modified existing examples to use LSI.  This prevents them from freezing on boards without an LSE crystal.  None of the examples seem to rely on high timing accuracy.
=> Use either LSI or LSE in RTC

CHANGELOG.md, Cargo.toml, examples/rtc_low_apb1.rs, examples/spi2.rs, src/rtc.rs, src/spi.rs
There are members of the stm32l0x1 subfamily that thave two SPIs.  In
particular the STM32l051 and the STM32l071.
Compile tested as:
cargo build --release --example spi2 --features mcu-STM32L051C8Tx
(builds)
cargo build --release --example spi2  --features mcu-STM32L031C6Tx
(fails to build, as this subfamily only has 1 SPI)
but not run on actual hardware.
=> Enable SPI2 on subset of stm32l0x1 devices

examples/pwr.rs, src/pwr.rs
Only category 1 devices of the STM32l0x1 family have a `lpds` bit on the power configuration register.  Categories 2 and above use the `lpsdsr` bit instead.  On STM32l0x2 and STM32l0x3, these two bits are aliased in the stm32l0 crate, so `cr.lpds()` and `cr.lpsdsr()` will modify the same bit.
Tested by compiling the `pwr.rs` example and running it on a STM32L051C8Tx. With the fix, the stop current is reduced by 13.4 uA.
cargo build --release --example pwr --features mcu-STM32L051C8Tx
The problem could not be measured in the `pwr.rs` example because in it the device is put into low-power sleep mode before entering stop. That code accidentally left the `lpsdsr` bit set which would then affect the stop mode that followed.  Fix this by properly exiting low power sleep.
=> Disable regulator when entering Stop on STM32l0x1

CHANGELOG.md, src/pwm.rs
Looking through some ST datasheets/RMs, TIM2 can output on the pins changed in this PR from the x011 range all the way up to the largest chips in the L0 family.
Closes #219
=> Enable all output pins for TIM2 on all devices

CHANGELOG.md, src/rcc.rs, src/spi.rs
I needed to use `OpenDrain` mode for SPI output pins, but the init for SPI were only defined for pins set to `Analog` (i.e. implicitly `PushPull`). Therefore I added `Output<OpenDrain>` as an alternative and also `Output<PushPull>` to allow for more explicit user peripheral setup code.
=> Allow pin modes OpenDrain and PushPull for SPI output pins

CHANGELOG.md, src/rcc.rs
Fixes #225 
There is no /32 AHB prescaler, but the old calculation code assumed there was, causing all calculated clock frequencies with an AHB prescaler > 16 to be off by a factor of 2.
Note that this only affects the frequencies stored in the `Clocks` struct, not the ones actually applied to the AHB frequency.
Page 194 of the [reference manual](https://www.st.com/resource/en/reference_manual/rm0367-ultralowpower-stm32l0x3-advanced-armbased-32bit-mcus-stmicroelectronics.pdf) shows mapping of register bits to prescaler factors. As far as I can see, those are implemented correctly.
=> Skip /32 AHB prescaler

src/exti.rs, src/gpio.rs, src/prelude.rs, src/serial.rs, src/spi.rs
Since Rust 1.73.0 there seems to be [a new deny-by-default lint](
https://doc.rust-lang.org/beta/rustc/lints/listing/deny-by-default.html#invalid-reference-casting) to catch invalid casting from references to mutable pointers.
As far as I understand the compiler is making assumptions that references are read only and passing those assumptions on to LLVM. The only way to tell the compiler to not make those assumptions is to use `UnsafeCell`.
So this PR is essentially wrapping those casts with `UnsafeCell` and getting the mutable pointer through it.
In addition to that I fixed some warnings from compiler lints and clippy lints.
=> Fix error "assigning to &T is undefined behavior" and clippy warnings

src/adc.rs
Implement the ACD self-calibration procedure, which is defined in the RM377 reference manual as follows:
The ADC has a calibration feature. During the procedure, the ADC calculates a calibration factor which is internally applied to the ADC until the next ADC power-off. The application must not use the ADC during calibration and must wait until it is complete.  Calibration should be performed before starting A/D conversion.
=> Implement ADC self-calibration

src/signature.rs
This fixes this warning:
warning: shared reference of mutable static is discouraged
--> stm32l0xx-hal/src/signature.rs:45:40
|
45 |         core::str::from_utf8_unchecked(&DEVICE_ID_STR)
|                                        ^^^^^^^^^^^^^^ shared reference of mutable static
|
= note: for more information, see issue #114447 <https://github.com/rust-lang/rust/issues/114447>
= note: reference of mutable static is a hard error from 2024 edition
= note: mutable statics can be written to by multiple threads: aliasing violations or data races will cause undefined behavior
= note: `#[warn(static_mut_ref)]` on by default
help: shared references are dangerous since if there's any kind of mutation of that static while the reference lives, that's UB; use `addr_of!` instead to create a raw pointer
=> Fix shared reference of mutable static warning
